name = "checkmd5"
description = "Improved MD5 aggregate file checker"
version = "0.103"

authors = ["AK-47"]
maintainers = ["none@example.com"]
licenses = "Apache-2.0"
website = ""
tags = ["checksum", "md5", "hash", "integrity", "checkisomd5", "implantisomd5", "md5sum"]

[build-switches]
"*".style_checks = [
	"-gnaty3", # Specify indentation level of 3
	"-gnatya", # Check attribute casing
	"-gnatyA", # Use of array index numbers in array attributes
	"-gnatyB", # Check Boolean operators
	"-gnatyb", # Blanks not allowed at statement end
	"-gnatyC", # Check comments
	"-gnaty-d", # Disable check no DOS line terminators present
	"-gnatye", # Check end/exit labels
	"-gnatyf", # No form feeds or vertical tabs
	"-gnatyh", # No horizontal tabs
	"-gnatyi", # Check if-then layout
	"-gnatyk", # Check keyword casing
	"-gnatyl", # Check layout
	"-gnatyM110", # Set maximum line length
	"-gnatyn", # Check casing of entities in Standard
	"-gnatyO", # Check that overriding subprograms are explicitly marked as such
	"-gnatyp", # Check pragma casing
	"-gnatyr", # Check identifier references casing
	"-gnatyS", # Check no statements after THEN/ELSE
	#"-gnatyt", # Check token spacing
	"-gnatyu", # Check unnecessary blank lines
	"-gnatyx", # Check extra parentheses
]
